/* embed.c -- turns shader source files into a C header of string literals.
 *
 * Run at build time (see Makefile); it keeps the shipped binary self-contained,
 * which matters because this engine's whole selling point is that it starts in
 * an environment where "install the assets" is not an option.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *sym_for(const char *path, const char *ext) {
	static char buf[128];
	const char *base = strrchr(path, '/');
	base = base ? base + 1 : path;
	strncpy(buf, base, sizeof(buf) - 1);
	buf[sizeof(buf) - 1] = 0;
	char *dot = strrchr(buf, '.');
	if (dot) *dot = 0;
	for (char *p = buf; *p; p++) {
		if (*p == '-' || *p == '.') *p = '_';
	}
	(void)ext;
	return buf;
}

int main(int argc, char **argv) {
	if (argc < 3) {
		fprintf(stderr, "usage: embed <files...> <out.h>\n");
		return 2;
	}
	FILE *out = fopen(argv[argc - 1], "wb");
	if (!out) { fprintf(stderr, "embed: cannot open %s\n", argv[argc - 1]); return 1; }
	fprintf(out, "/* generated by tools/embed.c -- do not edit */\n");
	fprintf(out, "#ifndef BERYL_GENERATED_SHADERS_H\n#define BERYL_GENERATED_SHADERS_H\n\n");
	for (int i = 1; i < argc - 1; i++) {
		FILE *f = fopen(argv[i], "rb");
		if (!f) { fprintf(stderr, "embed: missing %s\n", argv[i]); fclose(out); return 1; }
		fseek(f, 0, SEEK_END);
		long n = ftell(f);
		fseek(f, 0, SEEK_SET);
		char *data = (char *)malloc((size_t)n + 1);
		if (!data || fread(data, 1, (size_t)n, f) != (size_t)n) {
			fprintf(stderr, "embed: short read on %s\n", argv[i]);
			free(data); fclose(f); fclose(out);
			return 1;
		}
		fclose(f);
		data[n] = 0;
		const char *sym = sym_for(argv[i], NULL);
		fprintf(out, "/* %s (%ld bytes) */\nstatic const char beryl_src_%s[] =\n", argv[i], n, sym);
		/* Emit line-per-string-literal so a shader syntax error reports the same
		 * line number as the source file. */
		const char *p = data;
		while (*p) {
			const char *nl = strchr(p, '\n');
			int len = nl ? (int)(nl - p + 1) : (int)strlen(p);
			fputc('\t', out);
			fputc('"', out);
			for (int k = 0; k < len; k++) {
				char c = p[k];
				if (c == '"' || c == '\\') fputc('\\', out);
				if (c == '\n') { fputs("\\n", out); continue; }
				if (c == '\r' || c == '\t') continue;
				fputc(c, out);
			}
			fputs("\"\n", out);
			if (!nl) break;
			p += len;
		}
		fprintf(out, ";\n\n");
		free(data);
	}
	fprintf(out, "#endif\n");
	fclose(out);
	return 0;
}
